In [1]:
import numpy as np

In [ ]:
# where

In [3]:
arr= np.array([i for i in range (33,89,3)])
print(arr)

[33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87]


In [5]:
result=np.where (arr>50 ,'pass', 'fail')
print(result)

['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'pass' 'pass' 'pass' 'pass'
 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass']


In [ ]:
# select


In [ ]:
np.select()

In [6]:
condition=[arr>=75,arr>=50,arr<50]
check_list=['a+','b+','c+']
np.select(condition,check_list)

array(['c+', 'c+', 'c+', 'c+', 'c+', 'c+', 'b+', 'b+', 'b+', 'b+', 'b+',
       'b+', 'b+', 'b+', 'a+', 'a+', 'a+', 'a+', 'a+'], dtype='<U3')

In [10]:
# clip
arr1= np.arange(12,75,3)
arr1

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72])

In [ ]:
np.clip(arr1,18,60)

array([18, 18, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       60, 60, 60, 60])

In [13]:
arr2=np.clip(arr1,18,60)
np.unique(arr2,return_counts=True)

(array([18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]),
 array([3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5], dtype=int64))

In [14]:
np.bincount(arr2)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 5], dtype=int64)

In [15]:
np.bincount(np.array([0,1,1,2,2,2,2,3,3,4,4,4,5,5,5,5,5]))

array([1, 2, 4, 2, 3, 5], dtype=int64)

In [21]:
np.linspace(1,10, dtype=int,num=11)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.argsort(arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=int64)

In [23]:
np.argmin(arr2)

0

In [25]:
np.array([23,45,56,87,12,34,56]).argmin()

4

In [26]:
np.array([23,45,56,87,12,34,56]).argmax()

3

In [27]:
np.array([23,45,56,87,12,34,56]).sort()

In [29]:
arr3=np.array([23,45,56,87,12,34,56])
print(arr3)

[23 45 56 87 12 34 56]


In [31]:
np.sort(arr3,kind='quicksort')

array([12, 23, 34, 45, 56, 56, 87])

In [32]:
np.sort(arr3)[::-1]

array([87, 56, 56, 45, 34, 23, 12])

In [33]:
#partition
np.partition(arr3,2)

array([12, 23, 34, 87, 45, 56, 56])

array([18, 18, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       60, 60, 60, 60])

In [37]:
np.take(arr2,[1,4,8,9])


array([18, 24, 36, 39])

In [38]:
a= np.array([1,2,3,4,5,6,7,8,9])
b=np.array([11,12,13,14,15,16,17,18,19])

In [40]:
np.concatenate((a,b),axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [41]:
np.concatenate((a,b),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [42]:
a= np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
b=np.array([11,12,13,14,15,16,17,18,19]).reshape(3,3)

In [43]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [45]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [46]:
d=np.concatenate((a,b),axis=1)

In [49]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [17, 18, 19]]])

In [50]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [51]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])